x-mautic-volumes: &mautic-volumes
  - ./mautic/config:/var/www/html/config:z
  - ./mautic/logs:/var/www/html/var/logs:z
  - ./mautic/media/files:/var/www/html/docroot/media/files:z
  - ./mautic/media/images:/var/www/html/docroot/media/images:z
  - ./cron:/opt/mautic/cron:z

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u $$MYSQL_USER --password=$$(cat $${MYSQL_PASSWORD_FILE}) 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    secrets:
      - db_root_password
      - db_password

  mautic_web:
    image: mautic-test-local
    links:
      - db:mysql
    ports:
      - 8001:80
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_LOAD_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA}
      - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS}
      - MAUTIC_DB_PASSWORD_FILE=/run/secrets/db_password
    env_file:
      - .mautic_env
    healthcheck:
      test: curl http://localhost
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      - db
    secrets:
      - db_password

  mautic_cron:
    image: mautic-test-local
    links:
      - db:mysql
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron
      - MAUTIC_DB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    env_file:
      - .mautic_env
    depends_on:
      - mautic_web

  mautic_worker:
    image: mautic-test-local
    links:
      - db:mysql
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
      - MAUTIC_DB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    env_file:
      - .mautic_env
    depends_on:
      - mautic_web

secrets:
  db_password:
    file: ./db_password.txt
  db_root_password:
    file: ./db_root_password.txt

volumes:
  mysql-data:


networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-docker
