version: "2"
services:
  mautic:
    image: mautic/mautic
    depends_on:
      - mysql
    ports:
      - "80:80"
    environment:
      MAUTIC_DB_HOST: mysql
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mauticdbpass
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mauticdbpass

  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - sslcerts:/etc/ssl/private
    depends_on:
      - mautic
    entrypoint:
      - "bash"
      - "-c"
    command: |
      "if [ ! -f /etc/ssl/private/mautic.crt ]; then
        openssl req -x509 -newkey rsa:2048 -sha256 -nodes -keyout /etc/ssl/private/mautic.key -out /etc/ssl/private/mautic.crt -subj '/CN=mautic.local' -days 3650
        echo 'Created new ssl certificate'
      fi
      exec nginx -g 'daemon off;'"

volumes:
  sslcerts:
